# Site settings
title: Andre Harris
email: harrisandre682@gmail.com
url: https://harrisandre682.github.io/cyber-portfolio
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Incident & Response"
meta_author: Harris Andre

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2dd7b9 #80B3FF
  primary-rgb: "45,215,185" #"128,179,255"
  secondary: 48597a #FD6E8A
  secondary-dark: 001846 #A2122F

# Footer settings
footer:
  copyright: Andre Harris
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: www.linkedin.com/in/harrisandre682
  - title: github
    url: https://github.com/harrisandre682

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:harrisandre682@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Garland, Texas

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
